language: ruby

matrix:
  include:
    # https://docs.travis-ci.com/user/osx-ci-environment/
    # OS X 10.11 with Xcode 8
    - os: osx
      osx_image: xcode8
    # OS X 10.11 with Xcode 7.3
    - os: osx
      osx_image: xcode7.3
    # OS X 10.10 with Xcode 7.1
    - os: osx
      osx_image: xcode7.1
    # OS X 10.9 with Xcode 6.2
    - os: osx
      osx_image: beta-xcode6.2

before_install:
  - env
  - uname -a

install:
  - brew update
  - brew tap jubatus/jubatus

script:
  - brew install --verbose msgpack059.rb jubatus-mpio.rb jubatus-msgpack-rpc.rb jubatus-core.rb jubatus.rb
